# Generated by Django 5.2.3 on 2025-07-01 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50, null=True)),
                ('original_id', models.CharField(max_length=15)),
                ('intro', models.CharField(max_length=2000)),
                ('history', models.CharField(max_length=10000, null=True)),
                ('master_work', models.JSONField(default=list, null=True)),
                ('milestones', models.JSONField(default=list, null=True)),
                ('original_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50, null=True)),
                ('original_id', models.CharField(max_length=15)),
                ('original_url', models.CharField(max_length=50)),
                ('lyrics', models.CharField(max_length=2000)),
                ('songs', models.ManyToManyField(to='song.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('comment_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='发布时间')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song')),
            ],
        ),
    ]
