# Generated by Django 5.2.3 on 2025-07-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='history',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='master_work',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='milestones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
