# Generated by Django 5.2.3 on 2025-07-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_alter_artist_alias_alter_artist_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='intro',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='original_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='original_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
