# Generated by Django 5.2.3 on 2025-07-03 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_alter_artist_intro_alter_artist_original_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20, unique=True)),
                ('df', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SongSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20, unique=True)),
                ('df', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtistIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=20)),
                ('tf', models.PositiveIntegerField()),
                ('artist_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.artistsegment')),
            ],
        ),
        migrations.CreateModel(
            name='SongIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=20)),
                ('tf', models.PositiveIntegerField()),
                ('song_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.songsegment')),
            ],
        ),
    ]
