# Generated by Django 5.2.3 on 2025-07-03 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_artistsegment_songsegment_artistindex_songindex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistindex',
            old_name='song_id',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='songindex',
            old_name='song_id',
            new_name='article_id',
        ),
    ]
