# Generated by Django 5.2.3 on 2025-07-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_rename_song_id_artistindex_article_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistindex',
            name='article_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='songindex',
            name='article_id',
            field=models.PositiveIntegerField(),
        ),
    ]
